### PR TITLE
add multichannel info io test

### PR DESCRIPTION
**Pull request by faroit**
Updates the get_info unit test to also check a 2ch file. 
This test is expected to fail on the soundfile backend as revealed in #618

### CODE REVIEW

**Comment by faroit** [comment]
@vincentqb I added a `2ch_sinewave.wav` file to the assets dir. However, circle couldn't find the file. Anything i missed?

**Comment by vincentqb** [comment]
@mthrok -- can you comment on this?

**Comment by mthrok** [comment]
@faroit Could you try `common_utils.get_asset_path(filename)`?

@vincentqb I do not really know why the suggested code does not work, but I will follow up and get rid of `create_temp_assets_dir` as this is causing such unintuitive misbehavior later.

**Comment by faroit** [comment]
@mthrok did that (0b7f83df7720f3f9bdfcd95c8cbbaa6c4b5b1e20) didn't seem to help

**Comment by mthrok** [comment]
> @mthrok did that ([0b7f83d](https://github.com/pytorch/audio/commit/0b7f83df7720f3f9bdfcd95c8cbbaa6c4b5b1e20)) but didn't seem to help

It is very strange. I checked out your branch and `git` recognizes the file but the file is not there.

```
$ git clone https://github.com/pytorch/audio
$ cd audio
$ git fetch origin pull/639/head:get-info-pr
$ git checkout get-info-pr
$ git develop
$ git diff --name-only 3a4f356..0b7f83d
test/assets/2ch_sinewave.wav
test/test_io.py
$ ls test/assets/2ch_sinewave.wav
ls: cannot access 'test/assets/2ch_sinewave.wav': No such file or directory
```

What happens if you fresh clone `torchaudio` and does the above step?

Can you re-try creating the commit which added the file?

Also can you rebase? (although I do not think this is related.)

BTW please do not touch the class attributes and other tests. Some of them writes to files so those have to be using temporary directory as previously.

**Comment by mthrok** [comment]
> > @mthrok did that ([0b7f83d](https://github.com/pytorch/audio/commit/0b7f83df7720f3f9bdfcd95c8cbbaa6c4b5b1e20)) but didn't seem to help
> 
> It is very strange. I checked out your branch and `git` recognizes the file but the file is not there.
> 
> ```
> $ git clone https://github.com/pytorch/audio
> $ cd audio
> $ git fetch origin pull/639/head:get-info-pr
> $ git checkout get-info-pr
> $ git diff --name-only 3a4f356..0b7f83d
> test/assets/2ch_sinewave.wav
> test/test_io.py
> $ ls test/assets/2ch_sinewave.wav
> ls: cannot access 'test/assets/2ch_sinewave.wav': No such file or directory
> ```
> 
> What happens if you fresh clone `torchaudio` and does the above step?
> 
> Can you re-try creating the commit which added the file?
> 
> Also can you rebase? (although I do not think this is related.)
> 
> BTW please do not touch the class attributes and other tests. Some of them writes to files so those have to be using temporary directory as previously.

Actually, you changed class attribute and now the test shutdown behavior which cleans up **supposed to be TEMP** asset dir cleans up the actual asset dir, so the file in matter is deleted.

Please limit the change to `_test_5_get_info` only and revert the other changes you made to test class.

**Comment by mthrok** [comment]
So if you simply run `pytest test/test_io.py -v -k test_5`, the test runs (and fails).

```
$ pytest test/test_io.py -v -k test_5
============================================================================================================ test session starts =============================================================================================================
platform linux -- Python 3.8.2, pytest-5.4.1, py-1.8.1, pluggy-0.13.1 -- /home/moto/conda/envs/PY3.8-cuda101/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/scratch/moto/torchaudio/.hypothesis/examples')
rootdir: /scratch/moto/torchaudio
plugins: hypothesis-5.10.4
collected 8 items / 7 deselected / 1 selected

test/test_io.py::Test_LoadSave::test_5_get_info FAILED                                                                                                                                                                                 [100%]

================================================================================================================== FAILURES ==================================================================================================================
_______________________________________________________________________________________________________ Test_LoadSave.test_5_get_info ________________________________________________________________________________________________________

self = <test_io.Test_LoadSave testMethod=test_5_get_info>

    def test_5_get_info(self):
        for backend in BACKENDS:
            with self.subTest():
                with AudioBackendScope(backend):
>                   self._test_5_get_info()

test/test_io.py:240:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test/test_io.py:250: in _test_5_get_info
    self.assertEqual(ei.bits_per_sample, precision)
E   AssertionError: 32 != 16
========================================================================================================== short test summary info ===========================================================================================================
FAILED test/test_io.py::Test_LoadSave::test_5_get_info - AssertionError: 32 != 16
====================================================================================================== 1 failed, 7 deselected in 0.62s =======================================================================================================
```

But if you run the whole module the assets are modified and throws error.

```
$ pytest test/test_io.py -v
============================================================================================================ test session starts =============================================================================================================
platform linux -- Python 3.8.2, pytest-5.4.1, py-1.8.1, pluggy-0.13.1 -- /home/moto/conda/envs/PY3.8-cuda101/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/scratch/moto/torchaudio/.hypothesis/examples')
rootdir: /scratch/moto/torchaudio
plugins: hypothesis-5.10.4
collected 8 items

test/test_io.py::Test_LoadSave::test_1_save PASSED                                                                                                                                                                                     [ 12%]
test/test_io.py::Test_LoadSave::test_1_save_sine PASSED                                                                                                                                                                                [ 25%]
test/test_io.py::Test_LoadSave::test_2_load PASSED                                                                                                                                                                                     [ 37%]
test/test_io.py::Test_LoadSave::test_2_load_nonormalization PASSED                                                                                                                                                                     [ 50%]
test/test_io.py::Test_LoadSave::test_3_load_and_save_is_identity PASSED                                                                                                                                                                [ 62%]
test/test_io.py::Test_LoadSave::test_3_load_and_save_is_identity_across_backend SKIPPED                                                                                                                                                [ 75%]
test/test_io.py::Test_LoadSave::test_4_load_partial PASSED                                                                                                                                                                             [ 87%]
test/test_io.py::Test_LoadSave::test_5_get_info FAILED                                                                                                                                                                                 [100%]

================================================================================================================== FAILURES ==================================================================================================================
_______________________________________________________________________________________________________ Test_LoadSave.test_5_get_info ________________________________________________________________________________________________________

self = <test_io.Test_LoadSave testMethod=test_5_get_info>

    def test_5_get_info(self):
        for backend in BACKENDS:
            with self.subTest():
                with AudioBackendScope(backend):
>                   self._test_5_get_info()

test/test_io.py:240:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test/test_io.py:246: in _test_5_get_info
    si, ei = torchaudio.info(get_asset_path(input_path))
torchaudio/__init__.py:215: in info
    return _get_audio_backend_module().info(filepath)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

filepath = '/scratch/moto/torchaudio/test/assets/2ch_sinewave.wav'

    def info(filepath: str) -> Tuple[SignalInfo, EncodingInfo]:
        r"""See torchaudio.info"""

        import _torch_sox
>       return _torch_sox.get_info(filepath)
E       RuntimeError: Error opening audio file

torchaudio/_sox_backend.py:72: RuntimeError
------------------------------------------------------------------------------------------------------------ Captured stderr call ------------------------------------------------------------------------------------------------------------
formats: can't open input file `/scratch/moto/torchaudio/test/assets/2ch_sinewave.wav': No such file or directory
========================================================================================================== short test summary info ===========================================================================================================
FAILED test/test_io.py::Test_LoadSave::test_5_get_info - RuntimeError: Error opening audio file
=================================================================================================== 1 failed, 6 passed, 1 skipped in 0.82s ===================================================================================================
```

then

```
$ git status
On branch get-info-pr
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    test/assets/2ch_sinewave.wav
	modified:   test/assets/sinewave.wav
```

**Comment by mthrok** [comment]
@faroit 

I am seeing some very weird behavior from `test/test_io.py::Test_LoadSave` test suite.
So as a workaround can you define another test case in `test_io.py` and add your test there?

**Comment by faroit** [comment]
@mthrok sorry for the delay. I'm back on this now

**Comment by faroit** [comment]
@mthrok sorry, I didn't had more time to work on this. I this still relevant or already addressed in the recent overhaul of the scripable i/o backend?

**Comment by faroit** [comment]
@mthrok is this still relevant?

**Comment by mthrok** [comment]
> @mthrok is this still relevant?

Hi @faroit - I do believe not. For the new backends, I added the bunch of tests so they should work fine. And we did not change the behavior of the legacy backend.

**Comment by faroit** [comment]
@mthrok great, will close this one out then

**Pull request closed without merging**
