### PR TITLE
Turn on tests when building through conda-build

### PR DESCRIPTION
**Pull request by peterjc123**
Relates to #425

### CODE REVIEW

**Comment by peterjc123** [comment]
@vincentqb The Windows tests are enabled here. You may use this PR for testing purposes.

**Comment by vincentqb** [comment]
Rebased.

**Comment by vincentqb** [comment]
Is it intentional that `config.yml` and `config.yml.in` are not in sync, see [here](https://app.circleci.com/pipelines/github/pytorch/audio/1617/workflows/21e5dfaa-342b-4df8-9eb7-617352da4638/jobs/41498/steps)?

**Comment by peterjc123** [comment]
@vincentqb Nope, I used `python regenerate.py` but it doesn't work.

**Comment by vincentqb** [comment]
Rebased and regenerated yaml.

**Comment by vincentqb** [comment]
The windows build appear to get stuck at the same place:
```
Packaging torchaudio
INFO:conda_build.build:Packaging torchaudio
INFO conda_build.build:build(1571): Packaging torchaudio
Packaging torchaudio-0.6.0.dev20200501-py36
INFO:conda_build.build:Packaging torchaudio-0.6.0.dev20200501-py36
INFO conda_build.build:bundle_conda(891): Packaging torchaudio-0.6.0.dev20200501-py36
Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
WARNING:conda_build.build:Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
WARNING conda_build.build:bundle_conda(1042): Importing conda-verify failed.  Please be sure to test your packages.  conda install conda-verify to make this message go away.
compiling .pyc files...
number of files: 49
Fixing permissions
Packaged license file/s.
WARNING: Detecting which files contain PREFIX is slow, installing ripgrep makes it faster. 'conda install ripgrep'
TEST START: C:\tools\miniconda3\conda-bld\win-64\torchaudio-0.6.0.dev20200501-py36.tar.bz2
Renaming host prefix directory,  C:\tools\miniconda3\conda-bld\torchaudio_1588376129751\_h_env  to  C:\tools\miniconda3\conda-bld\torchaudio_1588376129751\host_prefix_moved_torchaudio-0.6.0.dev20200501-py36_win-64
Renaming work directory,  C:\tools\miniconda3\conda-bld\torchaudio_1588376129751\work  to  C:\tools\miniconda3\conda-bld\torchaudio_1588376129751\work_moved_torchaudio-0.6.0.dev20200501-py36_win-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\tools\miniconda3\conda-bld\torchaudio_1588376129751\_test_env


The following NEW packages will be INSTALLED:

    atomicwrites:       1.3.0-py36_1                                 
    attrs:              19.3.0-py_0                                  
    blas:               1.0-mkl                                      
    certifi:            2020.4.5.1-py36_0                            
    colorama:           0.4.3-py_0                                   
    cpuonly:            1.0-0                         pytorch-nightly
    icc_rt:             2019.0.0-h0cc432a_1                          
    importlib_metadata: 1.5.0-py36_0                                 
    intel-openmp:       2020.0-166                                   
    mkl:                2020.0-166                                   
    mkl-service:        2.3.0-py36hb782905_0                         
    mkl_fft:            1.0.15-py36h14836fe_0                        
    mkl_random:         1.1.0-py36h675688f_0                         
    more-itertools:     8.2.0-py_0                                   
    ninja:              1.9.0-py36h74a9793_0                         
    numpy:              1.18.1-py36h93ca92e_0                        
    numpy-base:         1.18.1-py36hc3f5095_1                        
    packaging:          20.3-py_0                                    
    pip:                20.0.2-py36_1                                
    pluggy:             0.13.1-py36_0                                
    py:                 1.8.1-py_0                                   
    pyparsing:          2.4.7-py_0                                   
    pytest:             5.4.1-py36_0                                 
    python:             3.6.10-h9f7ef89_1                            
    pytorch:            1.6.0.dev20200501-py3.6_cpu_0 pytorch-nightly [cpuonly]
    scipy:              1.4.1-py36h9439919_0                         
    setuptools:         46.1.3-py36_0                                
    six:                1.14.0-py36_0                                
    sqlite:             3.31.1-h2a8f88b_1                            
    torchaudio:         0.6.0.dev20200501-py36        local          
    vc:                 14.1-h0510ff6_4                              
    vs2015_runtime:     14.16.27012-hf0eaf9b_1                       
    wcwidth:            0.1.9-py_0                                   
    wheel:              0.34.2-py36_0                                
    wincertstore:       0.2-py36h7fe50ca_0                           
    zipp:               3.1.0-py_0                                   
    zlib:               1.2.11-h62dcd97_4                            

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
```

**Comment by peterjc123** [comment]
Yes, I'm looking into it. Looks like a bug in conda-build that blocks installing wheel packages and using pytest.

**Comment by peterjc123** [comment]
Well, it's weird because I cannot reproduce it on my machine.

**Comment by peterjc123** [comment]
@vincentqb Could you please give me some write permission to this repo so that I can debug using this [tutorial](https://github.com/pytorch/pytorch/wiki/Debugging-with-Remote-Desktop-on-CircleCI)?

**Comment by peterjc123** [comment]
@vincentqb It seems that the tests in `test_datasets.py` leads to the hang.

**Comment by peterjc123** [comment]
@vincentqb There's only one test failing now: `test_batch_mfcc`. Could you please look into it?

**Comment by vincentqb** [comment]
> @vincentqb There's only one test failing now: `test_batch_mfcc`. Could you please look into it?

I'm ok skipping this test on windows for now.
```
E       AssertionError: Not within tolerance rtol=1e-05 atol=1e-05 at input[1, 0, 2, 1384] (0.5488020181655884 vs. 0.5488258004188538) and 1 other locations (0.00%)
```

**Comment by peterjc123** [comment]
@vincentqb Test failures are unrelated. Do you want to get this into master?

**Comment by vincentqb** [comment]
Yes, I would like to merge this PR in. 

- [ ] nit: should we have the windows test under `ci/circleci: unittest_windows_py3.6`? there is no equivalent `ci/circleci: binary_windows_*_py3.6` that would make sense, right?
- [ ] once this PR as landed, we should update the upload the conda/wheel nightlies too :)

**Comment by peterjc123** [comment]
> [ ] nit: should we have the windows test under `ci/circleci: unittest_windows_py3.6`? there is no equivalent `ci/circleci: binary_windows_*_py3.6` that would make sense, right?

Yes, we should simply rename the prefix of the current working job into `unittest`.

> * once this PR as landed, we should update the upload the conda/wheel nightlies too :)
Yes, and that will fairly easy since torchaudio on Windows will be a Python-only package.

**Comment by peterjc123** [comment]
@vincentqb The unittest jobs are enabled in https://github.com/pytorch/audio/pull/604.

**Comment by vincentqb** [comment]
Closed by #604

**Pull request closed without merging**
