### PR TITLE
Fix lint

### PR DESCRIPTION
**Pull request by vincentqb**
- Fix 'file-does-not-end-in-newline' lint for `.flake8` file.
- Fix two typos.

### CODE REVIEW

**Review by zhangguanheng66 — APPROVED** [review]

**Comment by jieruan02** [comment]
Hi @vincentqb~ my PR #1212 has some same unittest failure in unittest_linux_cpu_py3.8 as yours caused by sox_io_backend.load(), which I was trying to find where my commit touch it. Do you happen to know what might be wrong for my case? Thank you!

**Comment by mthrok** [comment]
> Hi @vincentqb~ my PR #1212 has some same unittest failure in unittest_linux_cpu_py3.8 as this one, caused by sox_io_backend.load(), which I was trying to find where my commit touch it. Do you happen to know what might be wrong for my case? Thank you!

That test is flaky and I am wanting down the bug. You can ignore it or rerun the test until it is gone.

**Comment by jieruan02** [comment]
got it, thank you! I will go fix the style one and then rerun the test

**Comment by jieruan02** [comment]
> > Hi @vincentqb~ my PR #1212 has some same unittest failure in unittest_linux_cpu_py3.8 as this one, caused by sox_io_backend.load(), which I was trying to find where my commit touch it. Do you happen to know what might be wrong for my case? Thank you!
> 
> That test is flaky and I am wanting down the bug. You can ignore it or rerun the test until it is gone.

got it, thank you! I will go fix the style warning and rerun the test then

**Pull request merged**
