### PR TITLE
Run GPU test for all PRs and fix setup

### PR DESCRIPTION
**Pull request by mthrok**
- Enable GPU tests for all the PRs as we are seeing cases where CI jobs are failing due to bug or setup failure.
- Fix GPU jobs where environment variable were not passed from configuration

### CODE REVIEW

**Comment by mthrok** [comment]
wow why does python 3.9 get installed????

**Comment by mthrok** [comment]
Finding 1.
On Windows GPU VM, environment variables defined by `parameters` are not defined. This might be a bug on CCI side.

**Comment by mthrok** [comment]
Finding 2.
Same for Linux GPU VM. parameters are not propagated.

**Review by cpuhrsch — APPROVED** [review]

**Review by vincentqb — APPROVED** [review]
LGTM

**Pull request merged**
