### PR TITLE
0.3.2 point release.

### LINKED ISSUE #338: pip install forces install of old torch 1.3.0
I have torch 1.3.1 installed

`pip install torchaudio -f https://download.pytorch.org/whl/torch_stable.html` forces collecting of torch 1.3.0 even though a newer version is installed

This is an official installation way from README. If pip is mis-behaving, maybe a conda install should be recommended too

### PR DESCRIPTION
**Pull request by vincentqb**
Create 0.3.2 point release. To generate binaries: [wheels](https://github.com/pytorch/audio/pull/308#issuecomment-543188716) and [conda](https://github.com/pytorch/audio/pull/308#issuecomment-546020394) in #308. Once push of binaries is done, push [release notes](https://github.com/pytorch/audio/releases).

Permissions needed for point release:
- [x] Admin on [github repo](https://github.com/pytorch/audio/settings/collaboration)
- [x] [pytorch-builders](https://github.com/pytorch/audio/pull/354#issuecomment-561696554)
- [x] Write to [Amazon S3 pytorch  bucket](https://s3.console.aws.amazon.com/s3/buckets/pytorch/?region=eu-west-1&tab=overview)
- [x] [Maintainer on pypi](https://github.com/pytorch/audio/pull/308#issuecomment-543364259)
- [x] [Maintainer on conda pytorch channel](https://github.com/pytorch/audio/pull/308#issuecomment-545332458)
- [ ] ~Need CircleCI secrets?~

Fixes #338.

cc @seemethere

### CODE REVIEW

**Comment by vincentqb** [comment]
For reference, updated `.circleci/.config.yml.in`, ran `.circleci/regenerate.py`, and added the changes.

**Comment by vincentqb** [comment]
@ezyang -- I do not have permissions to upload to S3, is that the case? I see the following errors in the build.

```
nightly_binary_linux_wheel_py3.5 - Success
nightly_binary_linux_wheel_py3.5_upload - Unauthorized
```

And I do not see `torchaudio-0.3.2-*` in [the amazon bucket](https://s3.console.aws.amazon.com/s3/buckets/pytorch/whl/?region=eu-west-1&tab=overview).

**Comment by ezyang** [comment]
I've added you to pytorch-builders which should give you permissions to do so

**Comment by vincentqb** [comment]
> I've added you to pytorch-builders which should give you permissions to do so

@ezyang -- The tests now pass :) However, when I publish the wheels, I get an access denied error, see below. Note that the [file](https://pytorch.s3.amazonaws.com/whl/nightly/torchaudio-0.3.2-cp27-cp27m-linux_x86_64.whl
) does exist.
```
❯ cd builder/wheel
❯ ./publish_wheels.sh torchaudio-0.3.2

fatal error: An error occurred (404) when calling the HeadObject operation: Key "whl/nightly/torchaudio-0.3.2-cp27-cp27m-linux_x86_64.whl" does not exist

❯ aws s3 cp s3://pytorch/whl/nightly/torchaudio-0.3.2-cp27-cp27m-linux_x86_64.whl s3://pytorch/whl/torchaudio-0.3.2-cp27-cp27m-manylinux1_x86_64.whl --acl public-read

copy failed: s3://pytorch/whl/nightly/torchaudio-0.3.2-cp27-cp27m-linux_x86_64.whl to s3://pytorch/whl/torchaudio-0.3.2-cp27-cp27m-manylinux1_x86_64.whl An error occurred (AccessDenied) when calling the CopyObject operation: Access Denied
```
as done [here](https://github.com/pytorch/audio/pull/308#issuecomment-543188716).

**Comment by ezyang** [comment]
You need write access to the pytorch S3 bucket. @soumith can hook you up.

**Comment by seemethere** [comment]
@vincentqb You should now have access to push to the pytorch S3 bucket

**Comment by vincentqb** [comment]
@ezyang I've generated the [wheels](https://github.com/pytorch/audio/pull/308#issuecomment-543188716) and pushed them on pypi. For [conda](https://github.com/pytorch/audio/pull/308#issuecomment-546020394), [`builder_conda/publish_conda.sh`](https://github.com/pytorch/builder/blob/master/conda/publish_conda.sh) doesn't find the files (for torchaudio and torchtext, ok with torchvision) on conda (with conda search) and so the script isn't successful. Since the script was successful for 0.3.1, I'm wondering if you ran another script when preparing the binaries for conda. Which one would prepare/upload the `tar.gz` to [conda](https://anaconda.org/pytorch/torchaudio)?

**Comment by ezyang** [comment]
It looks like you waited too long and the release builds got GC'ed, at least, that's what this seems to suggest: https://anaconda.org/pytorch-nightly/torchaudio/files?page=3

**Comment by vincentqb** [comment]
> It looks like you waited too long and the release builds got GC'ed, at least, that's what this seems to suggest: https://anaconda.org/pytorch-nightly/torchaudio/files?page=3

Good point, reran CircleCI. Upload is currently failing though.

**Comment by ezyang** [comment]
We may be out of space on the org again. https://github.com/Anaconda-Platform/anaconda-client/issues/501 describes some situations which cause failure

**Comment by vincentqb** [comment]
> We may be out of space on the org again. [Anaconda-Platform/anaconda-client#501](https://github.com/Anaconda-Platform/anaconda-client/issues/501) describes some situations which cause failure

@ezyang 

- Logged in through [ssh](https://circleci.com/gh/pytorch/audio/23408).
- Applied patch from [comment](https://github.com/Anaconda-Platform/anaconda-client/issues/501#issuecomment-470742898) to
```
/opt/conda/pkgs/anaconda-client-1.7.2-py27_0/lib/python2.7/site-packages/binstar_client/commands/upload.py
```
- Reran upload command from `.circleci/config.yml`:
```
(base) root@70309b619fef:~# anaconda upload ~/workspace/torchaudio-0.3.2-py37.tar.bz2 -u pytorch-nightly --label main --no-progress --force
Using Anaconda API: https://api.anaconda.org
Using "pytorch-nightly" as upload username
Processing '/root/workspace/torchaudio-0.3.2-py37.tar.bz2'
Detecting file type...
File type is "conda"
Extracting conda package attributes for upload
Creating package "torchaudio"
Creating release "0.3.2"
Uploading file "pytorch-nightly/torchaudio/0.3.2/linux-64/torchaudio-0.3.2-py37.tar.bz2"
[WARNING] Distribution "linux-64/torchaudio-0.3.2-py37.tar.bz2" already exists. Removing.
Upload complete

conda package located at:
https://anaconda.org/pytorch-nightly/torchaudio
```
- File is listed on link in output :)

**Comment by vincentqb** [comment]
Triggering upload worked this time. Successfully pushed to conda.

**Comment by vincentqb** [comment]
Binaries are now available. Self-approving PR and merging.

**Pull request merged**
