### PR TITLE
Remove redundant dataset utilities 

### LINKED ISSUE #1081: Remove redundant dataset utilities
Some utilities in `torchaudio.datasets.utils` are no longer needed and we should get rid of them.

* [`unicode_csv_reader`](https://github.com/pytorch/audio/blob/a2085b85f04d693222297bf614a5e5b34de04986/torchaudio/datasets/utils.py#L21-L48)

* [`makedir_exist_ok`](https://github.com/pytorch/audio/blob/a2085b85f04d693222297bf614a5e5b34de04986/torchaudio/datasets/utils.py#L51-L61) (also mentioned in #477)

### PR DESCRIPTION
**Pull request by krishnakalyan3**
I have also addressed your comments on torch.random https://github.com/pytorch/audio/pull/1022#issuecomment-738500681. 
Fixes #1081

### CODE REVIEW

**Comment by mthrok** [comment]
Thanks for working on this but you need to get rid of all the internal use.
Please run tests by `pytest -vs test/torchaudio_unittest/datasets/`

**Comment by krishnakalyan3** [comment]
Hi, @mthrok looks like I am missing some context. Can you please let me know why `unicode_csv_reader` should be removed?.
If removed what should I be replacing it with?.

**Comment by mthrok** [comment]
These utilities were added (for internal use) to ease the difference between Python 2 and Python 3.

But now that Python 2 support is officially dropped, we do not need these utilities. Instead we can use the standard module as-is.
In Python 3 `os.makedirs` function has `exist_ok` argument, and csv module can handle unicode natively without the hack of changing the `field_limit_size`.

So we just need to replace the usages of these functions with standard module. Then we can remove the utility functions themselves.

**Comment by krishnakalyan3** [comment]
@mthrok can you please review this.

**Review by mthrok — APPROVED** [review]
Looks good. Thank you so much!

**Comment by krishnakalyan3** [comment]
@mthrok can you please recommend some other (easy - medium complexity) issues that I could work on?. 

Cheers,
Krishna

**Comment by mthrok** [comment]
@krishnakalyan3 Sure. Thanks for offering :) Let me think of an issue. Meanwhile, if you can join PyTorch's slack channel, we can discuss collaboration there too. Communication will be faster that way. https://pytorch.org/resources/

**Comment by mthrok** [comment]
@krishnakalyan3 

How about https://github.com/pytorch/audio/issues/910#issuecomment-708643874 ?
I consider this as *not easy* in terms of complexity because there are somewhat open-ended perspectives in the specification, so we need to iterate on the design.

**Pull request merged**
