### PR TITLE
Cleanup torch_sox.h/.cpp

### PR DESCRIPTION
**Pull request by jamarshon**
-Ran clangtidy on torch_sox.h/.cpp
-Add the header "torch_sox.h" to torch_sox.cpp. Previously torch_sox.h was not used by any files
-Reorder functions in torch_sox.h/.cpp to match the order they are defined in PYBIND11_MODULE

### CODE REVIEW

**Comment by cpuhrsch** [comment]
I'm generally in favor of code hygiene, but you're not adding any functionality and are significantly changing git blame. Typically we only format new code or code we touch and not all files at once. I know that it's cleaner, but if it's just for the sake of formatting then that stands in contrast of having code where the development is easily traced.

**Comment by jamarshon** [comment]
@cpuhrsch most of the git [blame](https://github.com/pytorch/audio/blame/adcbc8509662e770c01733b58a39a12a692e5de7/torchaudio/torch_sox.cpp) is maintained (compared to the [original](https://github.com/pytorch/audio/blame/master/torchaudio/torch_sox.cpp)). 

also I think most developer use git history instead of blame as it is more fine tuned so it should be fine

**Comment by cpuhrsch** [comment]
@jamarshon by history you mean log? blame is a lot more detailed than that. But even aside from that, if you now look at a range of commits the majority of changes will be dominated by this PR even though this PR doesn't fix any bugs nor adds any features but merely deals with aesthetics.

**Comment by jamarshon** [comment]
By history I mean [this](https://github.com/pytorch/audio/commits/master/torchaudio/torch_sox.h). I don't think preserving git blame should be a reason not to fix code (i.e. refactoring, etc.)

**Comment by cpuhrsch** [comment]
@jamarshon - It's used commonly and important to determine ownership and resolve bugs. Cosmetics will always come secondary to something like this.

**Pull request closed without merging**
