### PR TITLE
add image for specaugment docstring

### PR DESCRIPTION
**Pull request by vincentqb**
Adding images to docstring to illustrate SpecAugment added in #285 as suggested by moto. This could look good online?

specaugment_freq
specaugment_time

To regenerate:
```python
import torchaudio

filename = "steam-train-whistle-daniel_simon.wav"
waveform, sample_rate = torchaudio.load(filename)
specgram = torchaudio.transforms.Spectrogram(n_fft=1054)(waveform)

augmentations = torchaudio.transforms.TimeMasking(time_mask_param=100)
augmented = augmentations(specgram[0, ...].log())
plt.imshow(augmented.numpy(), cmap='gray');
# plt.axis('off')
plt.savefig('specaugment_time.jpg')

augmentations = torchaudio.transforms.FrequencyMasking(freq_mask_param=100)
augmented = augmentations(specgram[0, ...].log())
plt.imshow(augmented.numpy(), cmap='gray');
# plt.axis('off')
plt.savefig('specaugment_freq.jpg')
```

### CODE REVIEW

**Comment by cpuhrsch** [comment]
I'd add to the description a line describing the motivation behind this change.

**Comment by vincentqb** [comment]
Image in docstring in [pytorch](https://github.com/pytorch/pytorch/blob/77cd8e006b92a8faf90a1ffcfe601860df587726/torch/nn/modules/activation.py#L66-L79)

**Comment by cpuhrsch** [comment]
I think it's fine if the docstring can still stand by itself and the images are supplemental

**Comment by mthrok** [comment]
I think it would look better with a colormap other than grayscale.

https://matplotlib.org/cmocean/

**Comment by cpuhrsch** [comment]
On the color scheme: I'd play with it, but make sure it's still visible for people with color blindness and related

**Comment by mthrok** [comment]
Addressed by #1887

**Pull request closed without merging**
