### PR TITLE
Update AudioMetaData docstring with encoding values

### PR DESCRIPTION
**Pull request by astaff**
Question: I think the docstring is leaking Sphinx tags. Should we remove them?

### CODE REVIEW

**Comment by mthrok** [comment]
> Question: I think the docstring is leaking Sphinx tags. Should we remove them?

Where do you mean? The artifact looks good.
https://172095-90321822-gh.circle-artifacts.com/0/docs/backend.html

If you mean `[wikipedia]`,  `[xiph.org]` and other, they were residue from my copy-paste so we should remove it. Sorry about that.

**Comment by astaff** [comment]
spoke IRL: (1) revisit sphinx tags concern later. (2) removed links from docstring.

**Comment by mthrok** [comment]
> spoke IRL: (1) revisit sphinx tags concern later. (2) removed links from docstring.

`[wikipedia]` is still there. sorry...

**Comment by astaff** [comment]
Fixed.

**Review by mthrok — APPROVED** [review]
looks good. Thanks!

**Pull request merged**
