### PR TITLE
Automate Release-Only Changes

### PR DESCRIPTION
**Pull request by osalpekar**
First Pass for automating release-only changes.

Tested this in audio to ensure it works.

### CODE REVIEW

**Review by huydhn — APPROVED** [review]
LGTM!  Although I think this script, as it stands, doesn't need to be on a per-repo basis because replacing branch name is done everywhere.  But there might be more audio-specific steps later on I assume

**Comment by osalpekar** [comment]
@huydhn Yeah I was wondering something similar. There's nothing inherently audio-specific here, and with how the nova workflows are structured, I don't think there should be anything in the future. We can add such a script in test-infra, but might need to make some assumptions about the domain library setup. On the other hand, we could just make it a GHA, but might be overkill. Decided to just have this in each repo for now, but open to consolidation ideas.

**Comment by mthrok** [comment]
@osalpekar @huydhn We ususally have release-specific changes, which is removing prototypes https://github.com/pytorch/audio/pull/3592. It would be nice that it can be incorporated.

**Comment by osalpekar** [comment]
@mthrok Sure, let me look into doing that. I'm also wondering if there's something safer we could for for handling the prototypes in the release branch - we could make the prototype directory hidden (`_prototypes`) signaling the underlying components are not to be imported, and we could set a flag on the prototype unittests so that they are not run on the release-branch (or just have a separate CI job for them that doesn't run on the release branch). Let me know what you think!

**Pull request closed without merging**
