### PR TITLE
change 0.7.0 documentation to use a version selector

### PR DESCRIPTION
**Pull request by mattip**
Swap the static text "0.7.0" version for a link to the versions.html page

@brianjo

### CODE REVIEW

**Comment by mthrok** [comment]
Thanks!

**Comment by mthrok** [comment]
Updated the doc https://pytorch.org/audio/0.7.0/backend.html

Screen Shot 2021-02-23 at 13 24 22

**Comment by mattip** [comment]
@mthrok I am not sure what you mean by your comment about backend.html, is there a problem with the PR?

**Comment by mthrok** [comment]
Nothing is wrong. I just wanted to let you know that the doc is properly updated.
I thought I opened the index page and did not realized the thumbnail is backend.html.
Sorry about the confusion.

**Pull request merged**
