### PR TITLE
Fix vad to return zero output for zero input

### LINKED ISSUE #3668: F.vad on zero valued tensor returns nonempty tensor unexpectly.
### 🐛 Describe the bug

Here is a simple reproducible example.
```python
import torch
import torchaudio.functional as F

x = torch.zeros([16000])
y = F.vad(x, 16000)

print(f"input_size={x.size()}, ysize={y.size()}")
```

```
input_size=torch.Size([16000]), ysize=torch.Size([2400])
```

### Versions

Collecting environment information...
PyTorch version: 2.1.0+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 10 (buster) (x86_64)
GCC version: (Debian 8.3.0-6) 8.3.0
Clang version: 7.0.1-8+deb10u2 (tags/RELEASE_701/final)
CMake version: version 3.26.3
Libc version: glibc-2.28

Python version: 3.10.11 (main, Apr 20 2023, 00:02:35) [GCC 8.3.0] (64-bit runtime)
Python platform: Linux-5.4.56.bsk.10-amd64-x86_64-with-glibc2.28
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       40 bits physical, 48 bits virtual
CPU(s):              32
On-line CPU(s) list: 0-31
Thread(s) per core:  1
Core(s) per socket:  16
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Platinum 8260 CPU @ 2.40GHz
Stepping:            7
CPU MHz:             2399.998
BogoMIPS:            4799.99
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            36608K
NUMA node0 CPU(s):   0-15
NUMA node1 CPU(s):   16-31
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat umip pku ospke avx512_vnni md_clear arch_capabilities

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] onnx==1.13.1
[pip3] onnxruntime==1.14.1
[pip3] torch==2.1.0+cpu
[pip3] torchaudio==2.1.0+cpu
[pip3] torchvision==0.16.0+cpu
[pip3] triton==2.0.0
[conda] Could not collect

### PR DESCRIPTION
**Pull request by wasd96040501**
fix #3668 
Return empty result when not `has_triggered`.
Zeroed wav audio added to unit test.

### CODE REVIEW

**Review by mthrok — COMMENTED** [review]
Hi

Thanks for the PR. (and sorry for not responding to the original issue)

I have a few comments;
1. Please run `pre-commit run -a` to match the style of torchaudio.
2. We prefer not to add test assets, especially for cases where it's easy to create a synthetic one. Can you replace the zero assets with `torch.zeros`?
3. For zero audio, instead of performing sox compatibility check, I think we can directly check the correctness of the output value. Can we try that?
4. Can we replace these assets with synthetic data that are created on the fly?
We would like to remove these assets, thus

**Comment by wasd96040501** [comment]
Hi @mthrok , I have implemented the changes, please take a look😊

**Review by mthrok — COMMENTED** [review]
LGTM. Thanks. Will merge if tests pass.

**Comment by wasd96040501** [comment]
@mthrok It seems build conda failed. How can I fix this?

**Review by mthrok — APPROVED** [review]

**Comment by trangham283** [comment]
Hi, I think the current way to handle `not has_triggered` is wrong. It returns an empty tensor even if all the samples are non-zero. Here is a similar reproducible example to the one in https://github.com/pytorch/audio/issues/3668:

```
import torch
import torchaudio.functional as F
x = 10*torch.ones([16000])
y = F.vad(x, 16000)
print(f"input_size={x.size()}, ysize={y.size()}")
```

output:
`input_size=torch.Size([16000]), ysize=torch.Size([0])`

**Pull request merged**
