### PR TITLE
Refactor datasets test

### PR DESCRIPTION
**Pull request by mthrok**
Preparation for #814

### CODE REVIEW

**Comment by mthrok** [comment]
> LGTM, though can you clarify why renaming the `test_datasets.py` file?

0. They are practically same in the functionality.
1. in fb infrastructure, the test name is constructed based on the pass, so having `test_` prefix becomes `XXX_test_YYY`, which reads a bit wired. I found `XXX_YYY_test` is more readable.
2. moving the common path component to the last allows to decreases the required number of `tab` key pressed in terminal.

**Comment by mthrok** [comment]
Thanks!

**Comment by vincentqb** [comment]
> > LGTM, though can you clarify why renaming the `test_datasets.py` file?
> 
> 1. They are practically same in the functionality.
> 2. in fb infrastructure, the test name is constructed based on the pass, so having `test_` prefix becomes `XXX_test_YYY`, which reads a bit wired. I found `XXX_YYY_test` is more readable.
> 3. moving the common path component to the last allows to decreases the required number of `tab` key pressed in terminal.

That's fine by me, though are you planning to slowly migrate all other tests to this new naming convention?

**Comment by mthrok** [comment]
> > > LGTM, though can you clarify why renaming the `test_datasets.py` file?
> > 
> > 
> > 
> > 1. They are practically same in the functionality.
> > 2. in fb infrastructure, the test name is constructed based on the pass, so having `test_` prefix becomes `XXX_test_YYY`, which reads a bit wired. I found `XXX_YYY_test` is more readable.
> > 3. moving the common path component to the last allows to decreases the required number of `tab` key pressed in terminal.
> 
> That's fine by me, though are you planning to slowly migrate all other tests to this new naming convention?

Yes, when I am in need of moving a file.
I feel that we need to do a similar refactoring for `functionals` and `transforms` in a near future.

**Pull request merged**
