### PR TITLE
Remove multiprocessing from audio dataset tutorial

### LINKED ISSUE #2162: Remove multiprocessing from audio dataset tutorial
There are couple of audio tutorials in https://github.com/pytorch/audio/tree/main/examples/tutorials.

These `audio_XXX.py` were split from one big tutorial.

Since the original tutorial was long, and the dataset portion was at the very end of the tutorial, I put dataset download run in the background. `audio_datasets_tutorial` is now a standalone, simple tutorial, which no longer benefits from downloading dataset in subprocess. We can remove the subprocess portion.

https://github.com/pytorch/audio/blob/7a83f84fe4bde8eaca3124261bbc564472471095/examples/tutorials/audio_datasets_tutorial.py#L46-L53

## Steps
1. Remove the subprocessing part from the `tutorial/audio_datasets_tutorial.py`
2. Build the doc by running `GALLERY_PATTERN=audio_datasets_tutorial make html` in `docs` directory.
3. Check the resulting documentation in `build/html/index.html`.

## Setup
Please refer to CONTRIBUTING.md https://github.com/pytorch/audio/blob/main/CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by yonMaor**
Closes #2162

### CODE REVIEW

**Review by mthrok — APPROVED** [review]
Looks good. Thanks!

https://524800-90321822-gh.circle-artifacts.com/0/docs/tutorials/audio_datasets_tutorial.html

**Comment by yonMaor** [comment]
I see that a bunch of tests aren't passing, but they seem to be unrelated

**Comment by yonMaor** [comment]
@mthrok I can't merge the pull request, is this something that you're supposed to do?

**Comment by mthrok** [comment]
> @mthrok I can't merge the pull request, is this something that you're supposed to do?

Yes and it will be handled by some bot system. It will be merged soon.

**Comment by yonMaor** [comment]
oh ok, thanks!

**Pull request closed without merging**
