### PR TITLE
Add citation information in the documentation

### PR DESCRIPTION
**Pull request by yangarbiter**
Continuing #1947

### CODE REVIEW

**Comment by mthrok** [comment]
Can you double check that the rendering is as intended?

https://415138-90321822-gh.circle-artifacts.com/0/docs/index.html

**Review by mthrok — APPROVED** [review]

**Comment by yangarbiter** [comment]
Since the author list is long, different screen size may render slightly differently.

Screen Shot 2021-11-02 at 1 24 17 PM

Is there a way to get around this?

**Comment by nateanl** [comment]
Works for me. Maybe it's about the browser width.
image

**Review by nateanl — APPROVED** [review]

**Comment by mthrok** [comment]
> Is there a way to get around this?

I do not think so as long as `code` block is used. I think we can live with it.

**Comment by mthrok** [comment]
@nateanl Please do the honor and merge this.

**Pull request merged**
