### PR TITLE
Add citation information

### PR DESCRIPTION
**Pull request by yangarbiter**
Thanks @nateanl for uploading the [paper](https://arxiv.org/abs/2110.15018) to arxiv.

I've added the bibtex information in this PR.

Please check.

Thanks.

### CODE REVIEW

**Review by mthrok — APPROVED** [review]
Looks good and thanks for the work!

@nateanl @carolineechen @hwangjeff Can you give a second look?

**Review by hwangjeff — APPROVED** [review]

**Comment by mthrok** [comment]
@yangarbiter This PR is okay, and I think we can also mention this in the doc page. What do you think?

**Comment by yangarbiter** [comment]
@mthrok Sounds like a plan.
How about adding a section after the `PyTorch Libraries` section of [this page](https://pytorch.org/audio/stable/index.html).
I can initiate a separate PR for that.

**Comment by mthrok** [comment]
> @mthrok Sounds like a plan.
> How about adding a section after the `PyTorch Libraries` section of [this page](https://pytorch.org/audio/stable/index.html).
> I can initiate a separate PR for that.

Yeah, I think that's the good place to add.

**Pull request merged**
