### PR TITLE
Resolve setup issue of macOS CI Unittest on release/0.7

### PR DESCRIPTION
**Pull request by mthrok**
This PR resolves **dependency issue** of macOS unit test job setup step on `release/0.7` branch.

It turns out that on macOS and Python 3.6 and 3.7 `sox_effects.apply_effects_tensor` and `sox_effects.apply_effects_file` get stuck when used in DataLoader with multiple workers.

Looks like it is related to `OMP_NUM_THREADS` and DataLoader. Filed the issue here -> https://github.com/pytorch/pytorch/issues/46409 .

~~**However** notice that the way the CI jobs for PRs set up restricts to use PyTorch nightly build.
They might not be issue if the tests are ran with PyTorch RC 1.7.0. So I suggest to merge this PR first and let the CI job for `release/0.7` run and see if the stuck still happens. Then resolve it in the later PR.~~

### CODE REVIEW

**Comment by vincentqb** [comment]
If pytorch supported python 3.9 for 1.7 release (unfortunately doesn't, [here](https://github.com/pytorch/pytorch/issues/45731#issuecomment-702766653)), we could see if 3.9 also works, and this could give us confidence that this is something that has been resolved on python side?

**Comment by vincentqb** [comment]
Do you know when the test started failing? The original pull request #760 was fine, [here](https://app.circleci.com/pipelines/github/pytorch/audio?branch=pull%2F760).

**Review by cpuhrsch — APPROVED** [review]

**Review by vincentqb — APPROVED** [review]
As I understand, this essentially disables caching on the branch release. LGTM.

**Comment by mthrok** [comment]
thanks

**Pull request merged**
