### PR TITLE
Do not use nested namespaces in torchaudio/sox

### PR DESCRIPTION
**Pull request by malfet**
As it is a C++17 feature, and PyTorch and its extensions must still be C++14 compatible, as also specified in the top level CMakeLists.txt:
https://github.com/pytorch/audio/blob/8a0d7b36f7821fe55175f0d4e3ca6299b3817a6c/CMakeLists.txt#L30

Otherwise, it pollutes build logs with noisy
```
/Users/runner/work/test-infra/test-infra/pytorch/audio/torchaudio/csrc/sox/pybind/io.cpp:12:21: warning: nested namespace definition is a C++17 extension; define each namespace separately [-Wc++17-extensions]
namespace torchaudio::sox_io {
                    ^~~~~~~~
                     { namespace sox_io
```

### CODE REVIEW

**Review by atalman — APPROVED** [review]

**Comment by malfet** [comment]
This is still a work in progress, will add a few similar changes to the codebase, but goal is to reduce the noise

**Comment by mthrok** [comment]
@malfet Could you add `-modernize-concat-nested-namespaces` to [`.clang-tidy`](https://github.com/pytorch/audio/blob/main/.clang-tidy)? This change has been introduced unintentionally when following lint suggestion in fbcode.

**Comment by malfet** [comment]
> @malfet Could you add `-modernize-concat-nested-namespaces` to [`.clang-tidy`](https://github.com/pytorch/audio/blob/main/.clang-tidy)? This change has been introduced unintentionally when following lint suggestion in fbcode.

Do you mind if I'll add lintrunner(tool we use to lint pytorch core in OSS) config to torchaudio in a separate PR?

**Comment by mthrok** [comment]
> > @malfet Could you add `-modernize-concat-nested-namespaces` to [`.clang-tidy`](https://github.com/pytorch/audio/blob/main/.clang-tidy)? This change has been introduced unintentionally when following lint suggestion in fbcode.
> 
> Do you mind if I'll add lintrunner(tool we use to lint pytorch core in OSS) config to torchaudio in a separate PR?

Nope. Go ahead.

**Pull request closed without merging**
