### PR TITLE
0.3.1 point release

### PR DESCRIPTION
**Pull request by ezyang**
Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Comment by ezyang** [comment]
@vincentqb I merged it myself.

Re #261 it looks like it was only deprecated and not removed

**Comment by vincentqb** [comment]
@ezyang I notice that the version available on [pip](https://pypi.org/project/torchaudio/#history) is 0.3.0 which requires pytorch 1.2.0. I don't have access to the binaries. Can you update the version to 0.3.1?

**Comment by ezyang** [comment]
@soumith can you please give @vincentqb maintainership on torchaudio

**Comment by soumith** [comment]
@ezyang @vincentqb you are already an admin of the repo Vincent. You and christian are.

**Comment by vincentqb** [comment]
Yes, I am an admin on github. Do I need to be listed as a maintainer on pypi also? I see `ezyang` who is a maintainer on pypi written in [upload_wheels_to_pypi.sh](https://github.com/pytorch/builder/blob/master/wheel/upload_wheels_to_pypi.sh#L14), and my pypi username `vincentqb` is not on the list of maintainers [on pypi](https://pypi.org/project/torchaudio/#description).

**Comment by soumith** [comment]
oh, can add you on pypi. what is your pypi username?

**Comment by soumith** [comment]
you already gave your pypi username, i couldn't read. adding you in 1 min

**Comment by soumith** [comment]
added

**Comment by feinsteinben** [comment]
can you please upload this version to the "pytorch" conda channel as well?

**Comment by vincentqb** [comment]
@soumith -- my username is also "vincentqb" on anaconda.com.

**Comment by soumith** [comment]
@vincentqb added on conda

**Comment by vincentqb** [comment]
Uploaded using [builder/conda/publish_conda.sh](https://github.com/pytorch/builder/blob/master/conda/publish_conda.sh):

```
cd builder/conda
./publish_conda.sh torchaudio==0.3.1
```

@ezyang The error in #307 does not occur anymore, but when I print the version number I see `0.3.0+120f693` instead of `0.3.1` when installing with conda instead of pip.

conda:
```
conda create -n pytorch-conda python=3.7
conda activate pytorch-conda
conda install -c conda-forge sox
conda install -c pytorch torchaudio
python -c "import torch; print(torch.__version__); import torchaudio; print(torchaudio.__version__);"

1.3.0
0.3.0+120f693
```

pip:
```
conda create -n pytorch-pip python=3.7
conda activate pytorch-pip
pip install torchaudio
python -c "import torch; print(torch.__version__); import torchaudio; print(torchaudio.__version__);"

1.3.0
0.3.1
```

**Comment by feinsteinben** [comment]
@soumith @vincentqb 
thanks!

**Pull request merged**
