### PR TITLE
Improve Unit tests by moving random seeds to setUp

### PR DESCRIPTION
**Pull request by krishnakalyan3**
Following up on #2033.

### CODE REVIEW

**Review by nateanl — CHANGES_REQUESTED** [review]
Hi @krishnakalyan3, thanks for the PR! Some test methods still use `seed` when calling `get_whitenoise`. For example, the methods under [datasets test](https://github.com/pytorch/audio/blob/main/test/torchaudio_unittest/datasets/cmuarctic_test.py#L40). Could you also address them in this PR?

**Comment by krishnakalyan3** [comment]
@nateanl looks like the seed is being [changed](https://github.com/pytorch/audio/blob/main/test/torchaudio_unittest/datasets/cmuarctic_test.py#L51) in all dataset tests. Do we modify the random seed within the loop for all datasets?.

**Comment by mthrok** [comment]
> Hi @krishnakalyan3, thanks for the PR! Some test methods still use `seed` when calling `get_whitenoise`. For example, the methods under [datasets test](https://github.com/pytorch/audio/blob/main/test/torchaudio_unittest/datasets/cmuarctic_test.py#L40). Could you also address them in this PR?

@zhangguanheng66 This is intended design. The problem that the original PR was solving is automatically setting the seed of the library code that is run. If seed is not reset at the start of every test run, the test results end up depend on the order the test is executed. Test utilities allowing explicit seed is the right thing to do, otherwise it will implicitly depend on the global seed state, which could interfere the library code behavior.

@krishnakalyan3 the initial state of the PR looked fine. Can you revert the latest commit? We can merge it and follow up for the remaining.

**Comment by carolineechen** [comment]
completed in #2425 and #2436

**Pull request closed without merging**
