### PR TITLE
Versioned pages

### PR DESCRIPTION
**Pull request by mattip**
ping @brianjo. This enhancement to the gh-pages branch
- moves the documents around to allow versioning
- adds an index.html to redirect to stable/index.html
- adds a README.md 

Todo in future PRS:
- add a version selector like on the pytorch site
- automate doc building on a merge (to the "master" directory)
- automate doc building on a tag (to a numbered directory)
- rethink serving the `_static` content. After this PR, each directory uses its own `_static` subdirectory, i.e, `0.7/index.html` uses `0.7/_static` resources for stylesheets and javascript. It would be nice if the content were shared across versions, so that a styling update would be applied to the older versions automatically: `0.7/index.html` would use `/_static`.

It might be difficult to review this PR because of all the changed files. You can see it "live" on 
- the [README](https://github.com/mattip/audio/tree/gh-pages) after merging this branch to the gh-pages branch on my fork of the repo and 
- the [github pages root](https://mattip.github.io/index.html), [stable](https://mattip.github.io/audio/stable/index.html), [0.7](https://mattip.github.io/audio/0.7/index.html), and [master](https://mattip.github.io/audio/master/index.html). They all show the same content, the first will redirect to the second, and the third and fourth differ from the others only in the link in the address bar.

### CODE REVIEW

**Comment by mthrok** [comment]
Thanks, it looks good!

**Review by brianjo — APPROVED** [review]

**Comment by vincentqb** [comment]
> * the [github pages root](https://mattip.github.io/index.html)

I get 404 for this link. Expected?

**Review by vincentqb — APPROVED** [review]
LGTM, thx @brianjo for pointing out the link is not an issue here.

**Comment by mthrok** [comment]
@mattip Thank you so much!

**Comment by mthrok** [comment]
The website is updated https://pytorch.org/audio .

**Pull request merged**
