### PR TITLE
Improve the speed of torchaudio.compliance.kaldi.fbank

### PR DESCRIPTION
**Pull request by lawlict**
The old version computes fbank as follows:
```
# size: (m, padded_window_size // 2 + 1) --> (m, 1, padded_window_size // 2 + 1)
power_spectrum = power_spectrum.unsqueeze(1) 
# size: (num_mel_bins, padded_window_size // 2 + 1) --> (1, num_mel_bins, padded_window_size // 2 + 1)
mel_energies = mel_energies.unsqueeze(0)
# broadcast, dot product and sum up
mel_energies = (power_spectrum * mel_energies).sum(dim=2)
```
It equals:
```
mel_energies = torch.mm(power_spectrum, mel_energies.T).
```
Speed of computing 30s audios: 0.24s --> 0.06s.

### CODE REVIEW

**Comment by mthrok** [comment]
Hi @lawlict 

Thank you for making this PR. I am trying to reproduce your claim. Could you tell me what sampling rate you used in your benchmark?

**Comment by mthrok** [comment]
Using the following script, I get the following result;

```
$ OMP_NUM_THREADS=1 numactl --membind 0 --cpubind 0 python -m timeit -n 100 -r 5 -s """
import torch;
import torchaudio;
t = torch.randn(1, 32*44100);
""" 'torchaudio.compliance.kaldi.fbank(t)'
```

| Commit                    | Output |
|--------------------|------------------------------------------|
| This PR                     | 100 loops, best of 5: 96.8 msec per loop |
| master (2d879132) | 100 loops, best of 5: 218 msec per loop |

**Comment by lawlict** [comment]
Hi @mthrok 

The code i use is: 
```
import torch
import torchaudio
import time

kwargs = {
    "energy_floor": 1,
    "dither": 0,
    "frame_length": 25,
    "frame_shift": 10,
    "low_freq": 0,
    "high_freq": 8000,
    "num_mel_bins": 64,
    "preemphasis_coefficient": 0.97,
    "sample_frequency": 16000,
    "snip_edges": False,
    "subtract_mean": False,
    "use_log_fbank": True,
    "window_type": "hamming"
}

x = torch.rand(1, 16000 * 30)
tic = time.time()
for i in range(100):
    y = torchaudio.compliance.kaldi.fbank(x, **kwargs)
toc = time.time()
print((toc - tic) / 100)
```

Speed: 175ms (master) --> 31ms (this PR) on my local PC.

**Review by cpuhrsch — APPROVED** [review]

**Comment by mthrok** [comment]
@lawlict Thanks for the contribution!

**Pull request merged**
