### PR TITLE
Argument in griffinlim is not used

### LINKED ISSUE #1007: `normalized` argument in griffinlim is not used
## 🐛 Bug

`F.griffinlim`'s `normalized` func arg is not used. It should be removed or used.
If removing it, it should also be removed from `T.GriffinLim`.

### PR DESCRIPTION
**Pull request by krishnakalyan3**
Fixes #1007

### CODE REVIEW

**Review by mthrok — COMMENTED** [review]
Hi @krishnakalyan3 

Thanks for the contribution. As referred by https://github.com/pytorch/audio/issues/1007#issuecomment-728248036, can you put the warning at the beginning of the function?

**Comment by krishnakalyan3** [comment]
@mthrok please let me know if this is okay.

**Review by vincentqb — APPROVED** [review]
LGTM, thanks!

**Comment by krishnakalyan3** [comment]
Thanks for the quick review :)

**Pull request merged**
