### PR TITLE
Lint code style and remove PY2 compatibility

### PR DESCRIPTION
**Pull request by ankitdobhal**
## Description

Hi 👋 I ran the [DeepSource](https://deepsource.io/) static analyzer on the forked copy of this repo and found some [interesting code quality issues](https://deepsource.io/gh/ankitdobhal/audio/issues). This PR fixes a few of them.

## Summary of Fixes

- Fixed implicit Object Inheritance
- Remove unnecessary use of comprehension 
- Consider merging these comparisons with 'in'
- Consider using max

## Type of change

- [x] Antipattern
- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by ankitdobhal** [comment]
@mthrok review the updated PR and merge the fixes.

**Comment by mthrok** [comment]
@ankitdobhal 

This PR contains a different set of changes than #1351. 
Can you limit the change to the object inheritance and `list` and `dict` update from 41dbfd9f77debe588bbc8ea93fb75016b6837343?

**Comment by ankitdobhal** [comment]
> @ankitdobhal
> 
> This PR contains a different set of changes than #1351.
> Can you limit the change to the object inheritance and `list` and `dict` update from [41dbfd9](https://github.com/pytorch/audio/commit/41dbfd9f77debe588bbc8ea93fb75016b6837343)?

Thanks @mthrok for pointing out , I have updated the PR with new fixes.

**Review by mthrok — CHANGES_REQUESTED** [review]
Hi @ankitdobhal 

Thanks for the update.

Can you revert the changes in `torchaudio/functional/functional.py`?
Unlike the other changes, there is no issue in the code and it can impact the TorchScript IR (intermediate representation) when compiled.

**Comment by mthrok** [comment]
Thanks!

**Comment by ankitdobhal** [comment]
> Thanks!



> Thanks!

Thanks @mthrok .
I would like to propose something about DeepSource. 

Activating analysis will help you to continuously analyze repo for code quality issues and fix commonly occurring issues using the auto-fix feature. 

I would like to share some steps to activate [DeepSource](https://deepsource.io/) :

- Install DeepSource on your repository [here](https://deepsource.io/signup).
- create .deepsource.toml configuration which you can use to configure your analysis settings.
- Activate analysis [here](https://deepsource.io/pytorch/audio/issues).

**Comment by mthrok** [comment]
> I would like to propose something about DeepSource.

Thanks for the proposal but adding a new tool for our framework is not something torchaudio can decide on its own. The best way to make it adopted is to propose it in PyTorch repository https://github.com/pytorch/pytorch and get an approval, then we can discuss the adaptation steps.

**Pull request merged**
