### PR TITLE
Update theme for 0.7 docs

### PR DESCRIPTION
**Pull request by mattip**
Update the stable (0.7) docs for the newer theme, which reformats the top navbar

### CODE REVIEW

**Review by mthrok — APPROVED** [review]
token approval.

**Comment by mthrok** [comment]
At a glance, the font sizes are different. Is something changed functionally?

Screen Shot 2020-12-09 at 09 55 28

Screen Shot 2020-12-09 at 09 55 36

**Comment by brianjo** [comment]
The theme is pretty dynamic, so we make little updates to it all the time. Should be fine.

**Comment by mthrok** [comment]
> The theme is pretty dynamic, so we make little updates to it all the time. Should be fine.

Thanks for the clarification.

**Pull request merged**
