### PR TITLE
Move linux unit test CI job tools to dedicated directory

### PR DESCRIPTION
**Pull request by mthrok**

### CODE REVIEW

**Comment by mthrok** [comment]
@peterjc123  I need you to click "Submit Review" with Approve selected.

Screen Shot 2020-05-03 at 12 23 59

**Comment by peterjc123** [comment]
@mthrok Already done that. Is it because I don't have write access here?

**Comment by mthrok** [comment]
@peterjc123 
Oh I see. Sorry about that. Write access could be it but since I don't have admin access, I cannot add you as collaborator. 
I guess you can cherry-pick my commits and add them to your original PR.

**Comment by peterjc123** [comment]
Well, I cherry-picked this PR in mine. So I guess this one is not needed anymore.

**Comment by vincentqb** [comment]
Closed by #604

**Pull request closed without merging**
