### PR TITLE
Experimental windows builds

### PR DESCRIPTION
**Pull request by ezyang**
cc @peterjc123 

Signed-off-by: Edward Z. Yang <ezyang@fb.com>

### CODE REVIEW

**Comment by peterjc123** [comment]
@ezyang I believe this repo is not Windows-ready because it relies on sox that cannot be built statically.

**Comment by ezyang** [comment]
Yeah, I think I agree

**Comment by HsunGong** [comment]
> Yeah, I think I agree

Maybe use socket of `WSL` in order to get `sox` info ?? Seems feasible.

**Comment by peterjc123** [comment]
This is not a good idea. First, it requires users to install WSL. It's a win 10 only feature. Second, if there's WSL, why don't we just run code in WSL? Nevertheless, it may be helpful if you want to use native libraries with torchaudio. But apparently, this is not something we should do here.

**Comment by black-snow** [comment]
> Second, if there's WSL, why don't we just run code in WSL? 

Because it still has no CUDA support.

**Comment by peterjc123** [comment]
@black-snow They actually announced that several days ago. But the discussion here is rather old. We have torchaudio nightly packages for Windows now.

**Comment by black-snow** [comment]
> 
> 
> @black-snow They actually announced that several days ago. But the discussion here is rather old. We have torchaudio nightly packages for Windows now.

Thanks for the reply. Yes they did but only for WSL2 and for that you still have to be on insider/fast-ring (although the may update should be out soon).

How do I get the nightly? For now, I only need torchaudio.datasets (which uses `torchaudio.load` but I don't know if that requires sox already).

**Comment by peterjc123** [comment]
@black-snow 
```
# Conda
conda install -c pytorch-nightly torchaudio
# Pip
pip install -f https://download.pytorch.org/whl/nightly/torch_nightly.html torchaudio
```

**Comment by mthrok** [comment]
Addressed by https://github.com/pytorch/audio/pull/1345

**Pull request closed without merging**
