### PR TITLE
add cuctc tutorial, change blank skip threshould into prob

### PR DESCRIPTION
**Pull request by yuekaizhang**
Add a separate tutorial for cuctc.
Reslove #3096

### CODE REVIEW

**Comment by Adel-Moumen** [comment]
Hello @yuekaizhang, 

Many thanks for your CUDA Implementation. When it will be release in the pip install branch I will definitely make sure that we support it in SpeechBrain. 

In the meantime, can I ask you if you have any documentation that explain how you did your implementation ? This is something that could be relevant to the community to have a PyTorch version which does not involve custom CUDA kernels. 

Indeed, it is easier for people to directly modify PyTorch code than CUDA code when one wants to modify/implement research papers. Hence, I'm asking you if you could elaborate a little bit more on how we could re-implement what you did but with PyTorch directly. Many thanks!

Adel

**Comment by yuekaizhang** [comment]
> 

Thanks. @mthrok Do you know when it will be available in pip install ?

We would have a detailed documentation about how the cuda kernels were implemented in one or two months later.

Unfortunately, it can't be reimplemented with pure pytorch. (Or you would get worse or similar performace with current cpu version decoder in torchaudio.) Maybe you could try openai triton for python programmers.

**Comment by Adel-Moumen** [comment]
Ok good! 

Tbh I don't think Triton will be a good alternative to your implementation. The CPU kernel overheads hits really hard with Triton especially in this case where we have a for loop on the time steps. Btw did you tried CUDA Graph with your implementation? I guess it could improve the results by a lot since there is a for loop. 

And do you know if you are planning to integrate support for kenLM ? 

Thanks again.

**Comment by Adel-Moumen** [comment]
Thanks for the answers! Do you have a timeline in mind of when your code will be available in the pip install branch please?

**Comment by mthrok** [comment]
Hi folks

Sorry for the belated response. The next PyTorch release is scheduled at Oct 2023. https://dev-discuss.pytorch.org/t/pytorch-release-2-1-0/1271

The CUCTC code is accessible through nightly channel, so if you would like to try out, please refer to https://pytorch.org and install nightly build.

@yuekaizhang Sorry for not responding these days, I will review this soon.

**Pull request closed without merging**
