### PR TITLE
Add OPUS support to 0.6 release

### PR DESCRIPTION
**Pull request by mthrok**
Cherry-picking #753 and #755 for 0.6 release.

### CODE REVIEW

**Comment by vincentqb** [comment]
@seemethere -- do you have a link to the current planned dates for the final branch cuts for the next release for the domains?

**Comment by seemethere** [comment]
> @seemethere -- do you have a link to the current planned dates for the final branch cuts for the next release for the domains?

We're expecting a final RC for PyTorch by July 7th, so I'd expect domains to follow in the couple of days after that

**Comment by vincentqb** [comment]
> > @seemethere -- do you have a link to the current planned dates for the final branch cuts for the next release for the domains?
> 
> We're expecting a final RC for PyTorch by July 7th, so I'd expect domains to follow in the couple of days after that

At that point, it would make sense to simply re-cut the branch from master. Thoughts?

**Comment by mthrok** [comment]
thanks!

**Pull request merged**
