### PR TITLE
Added CodeQL and Bandit security checks as GitHub Actions

### PR DESCRIPTION
**Pull request by mstfbl**
This PR adds the [CodeQL ](https://securitylab.github.com/tools/codeql/)and [Bandit ](https://bandit.readthedocs.io/en/latest/)Security checks in the form of GitHub Action Workflows, where the two workflows run with each opened PR to the `master` branch.

For CodeQL, the task will upload CodeQL results under the "Security" GitHub repo tab and in the "Code scanning results" section.

For Bandit, the task will pass if no high-severity issues have been found in the repo (outside of the `./third-party` submodules directory).

### CODE REVIEW

**Comment by mstfbl** [comment]
I see that the `ci/circleci: circleci_consistency` build test is failing. Per the given instructions, I ran `python .circleci/regenerate.py`, however I'm only seeing these probably wrong changes occur:

In `.circleci/config.yml:
```yml
workflows:
  build:
    jobs:
      - circleci_consistency
      - binary_linux_wheel:
          conda_docker_image: pytorch/conda-builder:cpu
          cu_version: cpu
          name: binary_linux_wheel_py3.6_cpu
          python_version: &#39;3.6&#39;
          wheel_docker_image: pytorch/manylinux-cuda102
      - binary_linux_wheel:
          conda_docker_image: pytorch/conda-builder:cuda101
          cu_version: cu101
          name: binary_linux_wheel_py3.6_cu101
          python_version: &#39;3.6&#39;
```

Whereas before it was:

```yml
workflows:
  build:
    jobs:
      - circleci_consistency
      - binary_linux_wheel:
          conda_docker_image: pytorch/conda-builder:cpu
          cu_version: cpu
          name: binary_linux_wheel_py3.6_cpu
          python_version: '3.6'
          wheel_docker_image: pytorch/manylinux-cuda102
      - binary_linux_wheel:
          conda_docker_image: pytorch/conda-builder:cuda101
          cu_version: cu101
          name: binary_linux_wheel_py3.6_cu101
          python_version: '3.6'
```

What is the correct fix for this?

**Comment by mthrok** [comment]
> I see that the `ci/circleci: circleci_consistency` build test is failing. Per the given instructions, I ran `python .circleci/regenerate.py`, however I'm only seeing these probably wrong changes occur:
> 
> In `.circleci/config.yml:
> 
> ```yaml
> workflows:
>   build:
>     jobs:
>       - circleci_consistency
>       - binary_linux_wheel:
>           name: binary_linux_wheel_py3.6
>           python_version: &#39;3.6&#39;
>       - binary_linux_wheel:
>           name: binary_linux_wheel_py3.7
>           python_version: &#39;3.7&#39;
>       - binary_linux_wheel:
>           name: binary_linux_wheel_py3.8
>           python_version: &#39;3.8&#39;
> ```
> 
> Whereas before it was:
> 
> ```yaml
> workflows:
>   build:
>     jobs:
>       - circleci_consistency
>       - binary_linux_wheel:
>           name: binary_linux_wheel_py3.6
>           python_version: '3.6'
>       - binary_linux_wheel:
>           name: binary_linux_wheel_py3.7
>           python_version: '3.7'
>       - binary_linux_wheel:
>           name: binary_linux_wheel_py3.8
>           python_version: '3.8'
> ```
> 
> What is the correct fix for this?

I think `autoescape=True` is causing the issue.

**Comment by mstfbl** [comment]
@mthrok Thank you for pointing that out. I have fixed the `regenerate.py` `jinja` issue by making `autoescape=select_autoescape(enabled_extensions=('html', 'xml'))`.

**Review by malfet — APPROVED** [review]

**Comment by malfet** [comment]
Can you split this PR into 3:
 - One that fixes the bug with leaking URLContext
 - One that fixes semmelle bug in regenerate.py
 - Last one that adds new pipelines

**Comment by mstfbl** [comment]
I have removed the Bandit-specific changes from this PR. I've opened #1428 for the autoescape fix and #1429 for the URLContext response leak fix.

**Pull request merged**
