### PR TITLE
[Cherry-picked 0.9] Add name of paper before reference.

### PR DESCRIPTION
**Pull request by vincentqb**
Add name of paper before bibtex reference to make docstring readable to user of help command in python. This needs to be cherry-picked for release 0.9.

Follow-up to [comment](https://github.com/pytorch/audio/pull/1550#discussion_r646705780).

### CODE REVIEW

**Review by mthrok — APPROVED** [review]
Looks good. Thanks!

**Comment by mthrok** [comment]
Once this commit is cherry-picked to `release/0.9`, please update this PR title `[Cheery-picked 0.9] ...` and tag the new RC.

**Review by carolineechen — COMMENTED** [review]
there are also few places in `wav2vec2/models.py` that should also be updated (see [example](https://github.com/vincentqb/audio/blob/bibtex_title/torchaudio/models/wav2vec2/model.py#L10))

**Review by carolineechen — APPROVED** [review]

**Comment by vincentqb** [comment]
tag added, see [here](https://github.com/pytorch/audio/tags).

**Pull request merged**
